name: Testar com Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      # Definindo o banco de dados como serviço
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        
        #options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: |
        docker compose up --build -d

    - name: Run tests inside the container
      run: |
        docker-compose exec  backend python /backend/app/manage.py test

    - name: Shut down Docker Compose
      run: docker-compose down
