name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - uses: actions/checkout@v4

      # Passo 2: Configuração do Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      # Passo 4: Construir e iniciar os contêineres com Docker Compose
      - name: Build and start containers using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      # Passo 5: Executar testes (caso haja)
      - name: Run tests in the containers
        run: |
          # Exemplo de execução de testes no contêiner Django
          docker exec django-container pytest

          # Exemplo de execução de testes no contêiner Node.js
          docker exec node-container npm test

      # Passo 6: Parar os contêineres após os testes
      - name: Stop Docker containers
        run: |
          docker-compose -f docker-compose.yml down

