name: Testar com Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d db

    - name: Run tests inside the container
      run: |
        sh -c "python --version"
        #docker-compose exec -T backend python /backend/app/manage.py test

    - name: Shut down Docker Compose
      run: docker-compose down
